In [11]:
import pandas as pd

df = pd.read_csv('titanic.csv')
df.sample(4)

,Survived,Pclass,Name,Sex,Parents/Children Aboard,Siblings/Spouses Aboard,Fare,Age
169,0,1,Mr. Wyckoff Van der hoef,male,0,0,33.5000,61.0
177,0,2,Mr. Reginald Hale,male,0,0,13.0000,30.0
96,1,1,Mr. William Bertram Greenfield,male,1,0,63.3583,23.0
227,0,2,Mr. Arne Jonas Fahlstrom,male,0,0,13.0000,18.0

In [2]:
df.shape

(887, 8)

In [6]:
df.isnull().sum()

Survived                   0
Pclass                     0
Name                       0
Sex                        0
Parents/Children Aboard    0
Siblings/Spouses Aboard    0
Fare                       0
Age                        0
dtype: int64

In [9]:
df.Survived.value_counts()

Survived
0    545
1    342
Name: count, dtype: int64

In [12]:
df.drop("Name", axis="columns", inplace=True)
df.head()

,Survived,Pclass,Sex,Parents/Children Aboard,Siblings/Spouses Aboard,Fare,Age
0,0,3,male,0,1,7.2500,22.0
1,1,1,female,0,1,71.2833,38.0
2,1,3,female,0,0,7.9250,26.0
3,1,1,female,0,1,53.1000,35.0
4,0,3,male,0,0,8.0500,35.0

In [13]:
df['Sex'] = df['Sex'].map({'male': 1, 'female': 0})
df.head()

,Survived,Pclass,Sex,Parents/Children Aboard,Siblings/Spouses Aboard,Fare,Age
0,0,3,1,0,1,7.2500,22.0
1,1,1,0,0,1,71.2833,38.0
2,1,3,0,0,0,7.9250,26.0
3,1,1,0,0,1,53.1000,35.0
4,0,3,1,0,0,8.0500,35.0

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

X = df.drop('Survived', axis=1)
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=10)

In [23]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.83      0.84      0.84       112
           1       0.72      0.71      0.72        66

    accuracy                           0.79       178
   macro avg       0.78      0.78      0.78       178
weighted avg       0.79      0.79      0.79       178

In [24]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.85      0.89      0.87       112
           1       0.80      0.74      0.77        66

    accuracy                           0.84       178
   macro avg       0.83      0.82      0.82       178
weighted avg       0.84      0.84      0.84       178

In [25]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(n_estimators=100)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.87      0.93      0.90       112
           1       0.86      0.76      0.81        66

    accuracy                           0.87       178
   macro avg       0.86      0.84      0.85       178
weighted avg       0.86      0.87      0.86       178