# <font color="maroon"><h4 align="center">Pandas Concat and Merge: Exercise</h4></font>

In [2]:
import pandas as pd

### <font color="purple">**Question1**</font>
- Read the 3 csv files provided into seperate dataframes (movies.csv to df_movies, financials.csv to df_financials, languages.csv to df_languages).
- show the top 3 rows for each dataframe.

In [3]:
#for movies.csv
movies_df = pd.read_csv("movies.csv")

#for financials.csv
financial_df = pd.read_csv("financials.csv")

#for languages.csv
language_df = pd.read_csv("languages.csv")

In [4]:
#show top3 rows in df_movies
movies_df.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

In [5]:
#show top3 rows in df_financials
financial_df.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [6]:
#show top3 rows in df_languages
language_df.head()

   language_id lang_name
0            1     Hindi
1            2    Telugu
2            3   Kannada
3            4     Tamil
4            5   English

### <font color="purple">**Question2**</font>
- Read the csv file 'new_movies.csv' and store it into dataframe 'df_new_movies'
- Now, concat the dataframes [df_movies, df_new_movies] and store the results again to df_movies. Make sure to ignore the index while concatenating

In [7]:
#read the csv file: 'new_movies.csv'
df_new_movies = pd.read_csv("new_movies.csv")

#show the dataframe
df_new_movies

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,201,Pathaan,Bollywood,2023,6.6,Yash Raj Films,1
1,210,Vikram,Bollywood,2022,8.3,Raaj Kamal Films International,4
2,240,Black Panther: Wakanda Forever,Hollywood,200,6.9,Marvel Studios,5

In [8]:
#concat the two dataframes ['df_movies', df_new_movies]
movies_df = pd.concat([movies_df, df_new_movies], ignore_index=True)

#show the last 5 rows
movies_df.tail()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
37,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1
39,201,Pathaan,Bollywood,2023,6.6,Yash Raj Films,1
40,210,Vikram,Bollywood,2022,8.3,Raaj Kamal Films International,4
41,240,Black Panther: Wakanda Forever,Hollywood,200,6.9,Marvel Studios,5

### <font color="purple">**Question3**</font>

- Merge the dataframe df_movies with the df_languages on 'language_id'.
- Make sure you perform a **inner** join here.
- Store the result again to df_movies

In [9]:
#perform the join operation
movies_df = pd.merge(movies_df, language_df, on = 'language_id', how = "inner")

#show the top 5 rows
movies_df.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,lang_name
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,Kannada
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,English
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,English
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,English
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,English

### <font color="purple">**Question4**</font>

- Merge the dataframe df_movies with the df_financials on 'movie_id'.
- Make sure you perform a **left** join here.
- Store the result again to df_movies

In [10]:
#perform the join operation
movies_df = pd.merge(movies_df, financial_df, on = "movie_id", how = "left")

#show the last 5 rows
movies_df.tail()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,lang_name,budget,revenue,unit,currency
37,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1,Hindi,1.8,3.1,Billions,INR
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1,Hindi,500.0,950.0,Millions,INR
39,201,Pathaan,Bollywood,2023,6.6,Yash Raj Films,1,Hindi,NaN,NaN,NaN,NaN
40,210,Vikram,Bollywood,2022,8.3,Raaj Kamal Films International,4,Tamil,NaN,NaN,NaN,NaN
41,240,Black Panther: Wakanda Forever,Hollywood,200,6.9,Marvel Studios,5,English,NaN,NaN,NaN,NaN

### <font color="purple">**Question5**</font>

- Save the 'df_movies' dataframe with name 'final_complete_data.csv'.
- Only take the columns 'movie_id', 'title', 'lang_name', 'budget', 'revenue', 'currency'
- set the index to False while saving the dataframe

In [11]:
#save the dataframe to 'final_complete_data.csv'
movies_df = movies_df.to_csv("final_complete_data.csv", index = False, columns = ['movie_id', 'title', 'lang_name', 'budget', 'revenue', 'currency'])