In [2]:
import pandas as pd
ind_df = pd.DataFrame({
    'city' : ["Nashik", "Pune", "Mumbai"],
    'temperature' : [39, 49, 38],
    'humidity' : [78, 67, 81]
})

us_df = pd.DataFrame({
    'city' : ["New York", "Diego", "Chicago"],
    'temperature' : [69, 76, 98],
    'humidity' : [98, 87, 61]
})

In [5]:
df = pd.concat([ind_df,us_df], ignore_index = True)
df

       city  temperature  humidity
0    Nashik           39        78
1      Pune           49        67
2    Mumbai           38        81
3  New York           69        98
4     Diego           76        87
5   Chicago           98        61

In [6]:
df = pd.concat([ind_df, us_df], keys = ['India', 'US'])
df

             city  temperature  humidity
India 0    Nashik           39        78
      1      Pune           49        67
      2    Mumbai           38        81
US    0  New York           69        98
      1     Diego           76        87
      2   Chicago           98        61

In [21]:
temp_df = pd.DataFrame({
    'city' : ["Nashik", "Pune", "Mumbai", "Kolkata"],
    'temperature' : [39, 49, 38, 54]
}, index = [0, 1, 2, 3])
print(temp_df)

      city  temperature
0   Nashik           39
1     Pune           49
2   Mumbai           38
3  Kolkata           54

In [22]:
hum_df = pd.DataFrame({
    'city' : ["Nashik", "Pune", "Mumbai"],
    'humidity' : [79, 65, 71]
}, index = [0, 1, 2])
print(hum_df)

     city  humidity
0  Nashik        79
1    Pune        65
2  Mumbai        71

In [23]:
print(pd.concat([temp_df, hum_df], axis = 1))

      city  temperature    city  humidity
0   Nashik           39  Nashik      79.0
1     Pune           49    Pune      65.0
2   Mumbai           38  Mumbai      71.0
3  Kolkata           54     NaN       NaN

In [30]:
df = pd.merge(temp_df, hum_df, on = "city", how = "left")
print(df)

      city  temperature  humidity
0   Nashik           39      79.0
1     Pune           49      65.0
2   Mumbai           38      71.0
3  Kolkata           54       NaN