In [34]:
import pandas as pd
df = pd.read_csv("stock_data.csv", 
                 index_col = 0,
                 header = 0,
                 names = ["Index", "Stock_symbols", "Eps", "Revenue", "Price", "People"], 
                 na_values = ["Not available", "No", -1, "n.a"]
)
df

      Stock_symbols    Eps  Revenue   Price         People
Index
1             Goofl  27.82     87.0   845.0     larry page
2               WMT   4.61    484.0    65.0            NaN
3              MSFT    NaN     85.0    64.0     bill gates
4               RIL    NaN     50.0  1023.0  mukesh ambani
5              TATA   5.60      NaN     NaN     ratan aata

In [35]:
df["pe"] = df["Revenue"] / df["Eps"]
df

      Stock_symbols    Eps  Revenue   Price         People          pe
Index
1             Goofl  27.82     87.0   845.0     larry page    3.127247
2               WMT   4.61    484.0    65.0            NaN  104.989154
3              MSFT    NaN     85.0    64.0     bill gates         NaN
4               RIL    NaN     50.0  1023.0  mukesh ambani         NaN
5              TATA   5.60      NaN     NaN     ratan aata         NaN

In [37]:
df.to_csv("pe1.csv" , index = False)

In [4]:
import pandas as pd
df_movies = pd.read_excel("movies_db.xlsx", "movies") 
df_movies.head(4)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5

In [31]:
df_financials = pd.read_excel("movies_db.xlsx", "financials", converters = { 'currency' : corrected_currency}) 
df_financials.head(4)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      USD
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD

In [32]:
def corrected_currency(curr):
    if curr == "INR" or curr == "$$" or curr == "Dollars":
        return "USD"
    else:
        return "USD"

df_financials["currency"] = df_financials["currency"].apply(lambda x: corrected_currency(x))

In [33]:
df_financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      USD
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [34]:
df_financials["currrency"] = df_financials.drop(columns = "currrency", inplace = True)

KeyError: "['currrency'] not found in axis"

In [35]:
df_financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      USD
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [36]:
del df_financials["currrency"]

KeyError: 'currrency'

In [37]:
df_financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      USD
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [40]:
df_merged = pd.merge(df_movies, df_financials, on = "movie_id")
df_merged.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,USD
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.0,854.0,Millions,USD
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,250.0,670.0,Millions,USD

In [41]:
df_merged.to_excel("movies_merged.xlsx", sheet_name = "mearged", index = False)

In [45]:
df_stock = pd.DataFrame({
    'tickers' : ['gogl', 'msft', 'wmt'],
    'price' : [1200, 1498, 1204]
})
df_stock

  tickers  price
0    gogl   1200
1    msft   1498
2     wmt   1204