In [76]:
print("Hello World")

Hello World

In [115]:
import pandas as pd

df = pd.read_csv("weather_data.csv", parse_dates = ["day"])
type(df["day"][0])

pandas._libs.tslibs.timestamps.Timestamp

In [116]:
df.set_index("day", inplace = True)

In [117]:
df.temperature.mean()

np.float64(33.22)

In [70]:
df.fillna({
    "temperature": df["temperature"].mean(),
    "windspeed": df["windspeed"].mean(),
    "event" : "No Event",
}, inplace = True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [75]:
df.fillna(method = "bfill")

C:\Users\vaibh\AppData\Local\Temp\ipykernel_1652\3988041702.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "bfill")

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.1    Rain
2017-01-08         34.1        8.1   Sunny
2017-01-09         34.1        8.1  Cloudy
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [80]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [98]:
df.interpolate()

C:\Users\vaibh\AppData\Local\Temp\ipykernel_1652\4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

            temperature  windspeed   event
day
2017-01-01         32.0      6.000    Rain
2017-01-04         30.0      9.000   Sunny
2017-01-05         28.0      8.000    Snow
2017-01-06         30.0      7.000     NaN
2017-01-07         32.0      7.275    Rain
2017-01-08         32.7      7.550   Sunny
2017-01-09         33.4      7.825     NaN
2017-01-10         34.1      8.100  Cloudy
2017-01-11         40.0     12.000   Sunny

In [99]:
df.dropna(how = "all", inplace = True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [119]:
df.dropna(thresh = 1, inplace = True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [111]:
df

Empty DataFrame
Columns: [temperature, windspeed, event]
Index: []